// Database types matching the SQL schema.
// Manually written to match 001_initial_schema.sql.

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          auth_user_id: string;
          business_id: string;
          role: "admin" | "employee";
          username: string;
          must_change_password: boolean;
          account_status: "active" | "disabled";
          is_platform_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id: string;
          business_id: string;
          role?: "admin" | "employee";
          username: string;
          must_change_password?: boolean;
          account_status?: "active" | "disabled";
          is_platform_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string;
          business_id?: string;
          role?: "admin" | "employee";
          username?: string;
          must_change_password?: boolean;
          account_status?: "active" | "disabled";
          is_platform_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employees: {
        Row: {
          id: string;
          business_id: string;
          user_id: string;
          employee_number: string;
          full_name: string;
          phone: string | null;
          hourly_rate: number;
          mileage_rate: number;
          employment_status: "active" | "inactive";
          employment_type: "PERMANENT" | "PART_TIME" | "CASUAL";
          open_to_extra_shifts: boolean;
          odometer_tracking_enabled: boolean;
          task_proof_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id: string;
          employee_number: string;
          full_name: string;
          phone?: string | null;
          hourly_rate?: number;
          mileage_rate?: number;
          employment_status?: "active" | "inactive";
          employment_type?: "PERMANENT" | "PART_TIME" | "CASUAL";
          open_to_extra_shifts?: boolean;
          odometer_tracking_enabled?: boolean;
          task_proof_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string;
          employee_number?: string;
          full_name?: string;
          phone?: string | null;
          hourly_rate?: number;
          mileage_rate?: number;
          employment_status?: "active" | "inactive";
          employment_type?: "PERMANENT" | "PART_TIME" | "CASUAL";
          open_to_extra_shifts?: boolean;
          odometer_tracking_enabled?: boolean;
          task_proof_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_availability: {
        Row: {
          id: string;
          employee_id: string;
          business_id: string;
          day_of_week: number;
          start_time: string | null;
          end_time: string | null;
          is_available: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          business_id: string;
          day_of_week: number;
          start_time?: string | null;
          end_time?: string | null;
          is_available?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          business_id?: string;
          day_of_week?: number;
          start_time?: string | null;
          end_time?: string | null;
          is_available?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      shifts: {
        Row: {
          id: string;
          business_id: string;
          employee_id: string;
          date: string;
          scheduled_start: string;
          scheduled_finish: string;
          location: string | null;
          instructions: string | null;
          status: "pending" | "accepted" | "declined" | "completed" | "cancelled" | "updated_pending";
          event_id: string | null;
          recurring_group_id: string | null;
          is_recurring: boolean;
          recurrence_type: "NONE" | "NEXT_WEEK" | "WEEKLY_END_OF_MONTH" | "WEEKLY_CUSTOM_END";
          recurrence_end_date: string | null;
          require_odometer: boolean | null;
          created_by: string | null;
          updated_by: string | null;
          last_change_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          employee_id: string;
          date: string;
          scheduled_start: string;
          scheduled_finish: string;
          location?: string | null;
          instructions?: string | null;
          status?: "pending" | "accepted" | "declined" | "completed" | "cancelled" | "updated_pending";
          event_id?: string | null;
          recurring_group_id?: string | null;
          is_recurring?: boolean;
          recurrence_type?: "NONE" | "NEXT_WEEK" | "WEEKLY_END_OF_MONTH" | "WEEKLY_CUSTOM_END";
          recurrence_end_date?: string | null;
          require_odometer?: boolean | null;
          created_by?: string | null;
          updated_by?: string | null;
          last_change_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          employee_id?: string;
          date?: string;
          scheduled_start?: string;
          scheduled_finish?: string;
          location?: string | null;
          instructions?: string | null;
          status?: "pending" | "accepted" | "declined" | "completed" | "cancelled" | "updated_pending";
          event_id?: string | null;
          recurring_group_id?: string | null;
          is_recurring?: boolean;
          recurrence_type?: "NONE" | "NEXT_WEEK" | "WEEKLY_END_OF_MONTH" | "WEEKLY_CUSTOM_END";
          recurrence_end_date?: string | null;
          require_odometer?: boolean | null;
          created_by?: string | null;
          updated_by?: string | null;
          last_change_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      shift_attendance: {
        Row: {
          id: string;
          shift_id: string;
          employee_id: string;
          business_id: string;
          actual_start: string | null;
          actual_finish: string | null;
          attendance_status: "pending" | "working" | "completed";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shift_id: string;
          employee_id: string;
          business_id: string;
          actual_start?: string | null;
          actual_finish?: string | null;
          attendance_status?: "pending" | "working" | "completed";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shift_id?: string;
          employee_id?: string;
          business_id?: string;
          actual_start?: string | null;
          actual_finish?: string | null;
          attendance_status?: "pending" | "working" | "completed";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      odometer_submissions: {
        Row: {
          id: string;
          shift_id: string;
          employee_id: string;
          business_id: string;
          submission_type: "START" | "FINISH";
          photo_path: string;
          odometer_reading: number;
          server_timestamp: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          shift_id: string;
          employee_id: string;
          business_id: string;
          submission_type: "START" | "FINISH";
          photo_path: string;
          odometer_reading: number;
          server_timestamp?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          shift_id?: string;
          employee_id?: string;
          business_id?: string;
          submission_type?: "START" | "FINISH";
          photo_path?: string;
          odometer_reading?: number;
          server_timestamp?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      timesheets: {
        Row: {
          id: string;
          shift_id: string;
          employee_id: string;
          business_id: string;
          scheduled_start: string;
          scheduled_finish: string;
          actual_start: string;
          actual_finish: string;
          worked_minutes: number;
          start_odometer: number;
          finish_odometer: number;
          distance_km: number;
          hourly_rate_snapshot: number;
          mileage_rate_snapshot: number;
          wage_amount: number;
          mileage_amount: number;
          estimated_total: number;
          approved_total: number | null;
          status: "submitted" | "approved" | "needs_correction" | "correction_required" | "correction_submitted";
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          shift_id: string;
          employee_id: string;
          business_id: string;
          scheduled_start: string;
          scheduled_finish: string;
          actual_start: string;
          actual_finish: string;
          worked_minutes: number;
          start_odometer: number;
          finish_odometer: number;
          distance_km: number;
          hourly_rate_snapshot: number;
          mileage_rate_snapshot: number;
          wage_amount: number;
          mileage_amount: number;
          estimated_total: number;
          approved_total?: number | null;
          status?: "submitted" | "approved" | "needs_correction" | "correction_required" | "correction_submitted";
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          shift_id?: string;
          employee_id?: string;
          business_id?: string;
          scheduled_start?: string;
          scheduled_finish?: string;
          actual_start?: string;
          actual_finish?: string;
          worked_minutes?: number;
          start_odometer?: number;
          finish_odometer?: number;
          distance_km?: number;
          hourly_rate_snapshot?: number;
          mileage_rate_snapshot?: number;
          wage_amount?: number;
          mileage_amount?: number;
          estimated_total?: number;
          approved_total?: number | null;
          status?: "submitted" | "approved" | "needs_correction" | "correction_required" | "correction_submitted";
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          employee_id: string;
          business_id: string;
          period_start: string;
          period_end: string;
          total_hours: number;
          total_mileage: number;
          wage_amount: number;
          mileage_amount: number;
          total_amount: number;
          status: "unpaid" | "paid";
          payment_date: string | null;
          marked_paid_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          business_id: string;
          period_start: string;
          period_end: string;
          total_hours?: number;
          total_mileage?: number;
          wage_amount?: number;
          mileage_amount?: number;
          total_amount?: number;
          status?: "unpaid" | "paid";
          payment_date?: string | null;
          marked_paid_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          business_id?: string;
          period_start?: string;
          period_end?: string;
          total_hours?: number;
          total_mileage?: number;
          wage_amount?: number;
          mileage_amount?: number;
          total_amount?: number;
          status?: "unpaid" | "paid";
          payment_date?: string | null;
          marked_paid_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      businesses: {
        Row: {
          id: string;
          business_name: string;
          slug: string;
          email: string | null;
          phone: string | null;
          address: string | null;
          timezone: string;
          currency: string;
          week_starts_on: number;
          status: "ACTIVE" | "SUSPENDED" | "ARCHIVED";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_name: string;
          slug: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          timezone?: string;
          currency?: string;
          week_starts_on?: number;
          status?: "ACTIVE" | "SUSPENDED" | "ARCHIVED";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_name?: string;
          slug?: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          timezone?: string;
          currency?: string;
          week_starts_on?: number;
          status?: "ACTIVE" | "SUSPENDED" | "ARCHIVED";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staffing_events: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          event_date: string;
          location: string | null;
          start_time: string;
          finish_time: string;
          status: "DRAFT" | "OPEN" | "PARTIALLY_FILLED" | "FULLY_STAFFED" | "CANCELLED" | "COMPLETED";
          reminder_days_before: number | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          event_date: string;
          location?: string | null;
          start_time: string;
          finish_time: string;
          status?: "DRAFT" | "OPEN" | "PARTIALLY_FILLED" | "FULLY_STAFFED" | "CANCELLED" | "COMPLETED";
          reminder_days_before?: number | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          event_date?: string;
          location?: string | null;
          start_time?: string;
          finish_time?: string;
          status?: "DRAFT" | "OPEN" | "PARTIALLY_FILLED" | "FULLY_STAFFED" | "CANCELLED" | "COMPLETED";
          reminder_days_before?: number | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      event_staffing_requirements: {
        Row: {
          id: string;
          business_id: string;
          event_id: string;
          role: string;
          required_count: number;
          filled_count: number;
          start_time: string;
          finish_time: string;
          instructions: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          event_id: string;
          role?: string;
          required_count: number;
          filled_count?: number;
          start_time: string;
          finish_time: string;
          instructions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          event_id?: string;
          role?: string;
          required_count?: number;
          filled_count?: number;
          start_time?: string;
          finish_time?: string;
          instructions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      open_shift_offers: {
        Row: {
          id: string;
          business_id: string;
          event_id: string;
          requirement_id: string;
          role: string;
          positions_required: number;
          positions_filled: number;
          status: "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CLOSED" | "CANCELLED";
          expires_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          event_id: string;
          requirement_id: string;
          role?: string;
          positions_required: number;
          positions_filled?: number;
          status?: "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CLOSED" | "CANCELLED";
          expires_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          event_id?: string;
          requirement_id?: string;
          role?: string;
          positions_required?: number;
          positions_filled?: number;
          status?: "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CLOSED" | "CANCELLED";
          expires_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      open_shift_offer_recipients: {
        Row: {
          id: string;
          business_id: string;
          offer_id: string;
          employee_id: string;
          status: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED" | "CLOSED";
          shift_id: string | null;
          sent_at: string;
          responded_at: string | null;
        };
        Insert: {
          id?: string;
          business_id: string;
          offer_id: string;
          employee_id: string;
          status?: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED" | "CLOSED";
          shift_id?: string | null;
          sent_at?: string;
          responded_at?: string | null;
        };
        Update: {
          id?: string;
          business_id?: string;
          offer_id?: string;
          employee_id?: string;
          status?: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED" | "CLOSED";
          shift_id?: string | null;
          sent_at?: string;
          responded_at?: string | null;
        };
        Relationships: [];
      };
      event_audit_log: {
        Row: {
          id: string;
          business_id: string;
          event_id: string;
          action: string;
          details: Record<string, unknown> | null;
          performed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          event_id: string;
          action: string;
          details?: Record<string, unknown> | null;
          performed_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          event_id?: string;
          action?: string;
          details?: Record<string, unknown> | null;
          performed_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      business_members: {
        Row: {
          id: string;
          business_id: string;
          user_id: string;
          role: "OWNER" | "ADMIN" | "EMPLOYEE";
          status: "ACTIVE" | "INACTIVE" | "INVITED";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id: string;
          role: "OWNER" | "ADMIN" | "EMPLOYEE";
          status?: "ACTIVE" | "INACTIVE" | "INVITED";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string;
          role?: "OWNER" | "ADMIN" | "EMPLOYEE";
          status?: "ACTIVE" | "INACTIVE" | "INVITED";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      shift_audit_log: {
        Row: {
          id: string;
          shift_id: string | null;
          deleted_shift_id: string | null;
          employee_id: string;
          business_id: string;
          changed_by: string;
          changed_at: string;
          original_date: string | null;
          new_date: string | null;
          original_start: string | null;
          new_start: string | null;
          original_finish: string | null;
          new_finish: string | null;
          original_location: string | null;
          new_location: string | null;
          original_instructions: string | null;
          new_instructions: string | null;
          original_employee_id: string | null;
          new_employee_id: string | null;
          original_status: string | null;
          new_status: string | null;
          change_reason: string;
          change_notes: string | null;
          override_reason: string | null;
          required_reconfirmation: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          shift_id?: string | null;
          deleted_shift_id?: string | null;
          employee_id: string;
          business_id: string;
          changed_by: string;
          changed_at?: string;
          original_date?: string | null;
          new_date?: string | null;
          original_start?: string | null;
          new_start?: string | null;
          original_finish?: string | null;
          new_finish?: string | null;
          original_location?: string | null;
          new_location?: string | null;
          original_instructions?: string | null;
          new_instructions?: string | null;
          original_employee_id?: string | null;
          new_employee_id?: string | null;
          original_status?: string | null;
          new_status?: string | null;
          change_reason: string;
          change_notes?: string | null;
          override_reason?: string | null;
          required_reconfirmation?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          shift_id?: string | null;
          deleted_shift_id?: string | null;
          employee_id?: string;
          business_id?: string;
          changed_by?: string;
          changed_at?: string;
          original_date?: string | null;
          new_date?: string | null;
          original_start?: string | null;
          new_start?: string | null;
          original_finish?: string | null;
          new_finish?: string | null;
          original_location?: string | null;
          new_location?: string | null;
          original_instructions?: string | null;
          new_instructions?: string | null;
          original_employee_id?: string | null;
          new_employee_id?: string | null;
          original_status?: string | null;
          new_status?: string | null;
          change_reason?: string;
          change_notes?: string | null;
          override_reason?: string | null;
          required_reconfirmation?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      task_proof_templates: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      task_proof_template_items: {
        Row: {
          id: string;
          template_id: string;
          proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          instruction: string | null;
          minimum_photos: number;
          maximum_photos: number;
          is_required: boolean;
          allow_employee_note: boolean;
          allow_finish_without_proof: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          instruction?: string | null;
          minimum_photos?: number;
          maximum_photos?: number;
          is_required?: boolean;
          allow_employee_note?: boolean;
          allow_finish_without_proof?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          proof_type?: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          instruction?: string | null;
          minimum_photos?: number;
          maximum_photos?: number;
          is_required?: boolean;
          allow_employee_note?: boolean;
          allow_finish_without_proof?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      task_proof_requirements: {
        Row: {
          id: string;
          business_id: string;
          shift_id: string;
          proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          instruction: string | null;
          minimum_photos: number;
          maximum_photos: number;
          is_required: boolean;
          allow_employee_note: boolean;
          allow_finish_without_proof: boolean;
          sort_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          shift_id: string;
          proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          instruction?: string | null;
          minimum_photos?: number;
          maximum_photos?: number;
          is_required?: boolean;
          allow_employee_note?: boolean;
          allow_finish_without_proof?: boolean;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          shift_id?: string;
          proof_type?: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          instruction?: string | null;
          minimum_photos?: number;
          maximum_photos?: number;
          is_required?: boolean;
          allow_employee_note?: boolean;
          allow_finish_without_proof?: boolean;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      task_proof_submissions: {
        Row: {
          id: string;
          business_id: string;
          shift_id: string;
          employee_id: string;
          requirement_id: string;
          proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          photo_path: string;
          employee_note: string | null;
          server_timestamp: string;
          status: "SUBMITTED" | "REPLACED" | "NEEDS_REVIEW" | "CORRECTION_REQUIRED" | "APPROVED";
          correction_reason: string | null;
          correction_requested_by: string | null;
          correction_requested_at: string | null;
          replaces_submission_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          shift_id: string;
          employee_id: string;
          requirement_id: string;
          proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          photo_path: string;
          employee_note?: string | null;
          server_timestamp?: string;
          status?: "SUBMITTED" | "REPLACED" | "NEEDS_REVIEW" | "CORRECTION_REQUIRED" | "APPROVED";
          correction_reason?: string | null;
          correction_requested_by?: string | null;
          correction_requested_at?: string | null;
          replaces_submission_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          shift_id?: string;
          employee_id?: string;
          requirement_id?: string;
          proof_type?: "BEFORE" | "DURING" | "AFTER" | "OTHER";
          photo_path?: string;
          employee_note?: string | null;
          server_timestamp?: string;
          status?: "SUBMITTED" | "REPLACED" | "NEEDS_REVIEW" | "CORRECTION_REQUIRED" | "APPROVED";
          correction_reason?: string | null;
          correction_requested_by?: string | null;
          correction_requested_at?: string | null;
          replaces_submission_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      accept_open_shift_offer: {
        Args: {
          p_offer_id: string;
          p_recipient_id: string;
          p_employee_id: string;
          p_business_id: string;
        };
        Returns: {
          success: boolean;
          error?: string;
          positions_filled?: number;
          positions_required?: number;
          offer_now_filled?: boolean;
        };
      };
    };
    Enums: {
      user_role: "admin" | "employee";
      account_status: "active" | "disabled";
      employment_status: "active" | "inactive";
      shift_status: "pending" | "accepted" | "declined" | "completed" | "cancelled" | "updated_pending";
      attendance_status: "pending" | "working" | "completed";
      submission_type: "START" | "FINISH";
      timesheet_status: "submitted" | "approved" | "needs_correction" | "correction_required" | "correction_submitted";
      payment_status: "unpaid" | "paid";
      recurrence_type: "NONE" | "NEXT_WEEK" | "WEEKLY_END_OF_MONTH" | "WEEKLY_CUSTOM_END";
      staffing_event_status: "DRAFT" | "OPEN" | "PARTIALLY_FILLED" | "FULLY_STAFFED" | "CANCELLED" | "COMPLETED";
      open_offer_status: "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CLOSED" | "CANCELLED";
      offer_recipient_status: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED" | "CLOSED";
      employment_type: "PERMANENT" | "PART_TIME" | "CASUAL";
      proof_type: "BEFORE" | "DURING" | "AFTER" | "OTHER";
      proof_submission_status: "SUBMITTED" | "REPLACED" | "NEEDS_REVIEW" | "CORRECTION_REQUIRED" | "APPROVED";
    };
  };
};
